######### pangenie ready multi-allelic and bi-allelic VCFs with ID annotations
graph_vcf:
 cactus-chm13: /gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/results/data/vcf/cactus-100000/cactus_filtered_ids.vcf.gz
 hgsvc: /gpfs/project/ebler/hgsvc/experiments/genotyping-experiments-revision/data/generated/vcf/pav-freeze4/multisample-vcfs/pav-all-samples.vcf.gz

biallelic_vcf:
 cactus-chm13: /gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/results/data/vcf/cactus-100000/cactus_filtered_ids_biallelic.vcf.gz
 hgsvc: /gpfs/project/ebler/hgsvc/experiments/genotyping-experiments-revision/data/downloaded/vcf/pav/freeze4.all-biallelic-parents.vcf.gz

variants:
 cactus-chm13:
  - snp 
  - indels
  - large-deletion
  - large-insertion
  - large-complex
 hgsvc:
  - snp 
  - indels
  - large-deletion
  - large-insertion


panel_samples:
 cactus-chm13:
  - HG00438
  - HG00621
  - HG00673
  - HG00733
  - HG00735
  - HG00741
  - HG01071
  - HG01106
  - HG01109
  - HG01123
  - HG01175
  - HG01243
  - HG01258
  - HG01358
  - HG01361
  - HG01891
  - HG01928
  - HG01952
  - HG01978
  - HG02055
  - HG02080
  - HG02109
  - HG02145
  - HG02148
  - HG02257
  - HG02486
  - HG02559
  - HG02572
  - HG02622
  - HG02630
  - HG02717
  - HG02723
  - HG02818
  - HG02886
  - HG03098
  - HG03453
  - HG03486
  - HG03492
  - HG03516
  - HG03540
  - HG03579
  - NA18906
  - NA20129
  - NA21309
 hgsvc:
  - HG00731
  - HG00732
  - HG00512
  - HG00513
  - NA19238
  - NA19239
  - HG03125
  - NA12878 
  - HG03486
  - HG02818
  - HG03065
  - HG03683
  - HG02011
  - HG03371
  - NA12329
  - HG00171
  - NA18939
  - HG03732
  - HG00096
  - NA20847
  - HG03009
  - NA20509
  - HG00864
  - HG01505
  - NA18534
  - NA19650
  - HG02587
  - HG01596
  - HG01114
  - NA19983
  - HG02492


######### reference genomes on which VCFs are based and corresponding repeat annotations
reference:
 cactus-chm13: external-data/chm13.fa 
 hgsvc: external-data/hg38.fa 

repeat_regions:
 cactus-chm13: external-data/chm13v2.0_RepeatMasker_4.1.2p1.2022Apr14.bed
 hgsvc: external-data/ucsc-simple-repeats.bed

######### leave-one-out samples to be considered
leave_one_out_samples:
 cactus-chm13:
  - HG00438
  - HG00733
  - HG02717
  - NA20129
  - HG03453 
 hgsvc:
  - HG00731
  - HG00512
  - NA19238
  - NA19650
  - HG02492

# location where 1000G reads are stored
read_dir_related: /gpfs/project/projects/medbioinf/data/illumina_nygc/output/reduced/PRJEB36890.698/
read_dir_unrelated: /gpfs/project/projects/medbioinf/data/illumina_nygc/output/reduced/PRJEB31736.2504/

sample_index_related: /gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/resources/PRJEB36890.698.ready.tsv
sample_index_unrelated: /gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/resources/PRJEB31736.2504.ready.tsv

trios: /gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/resources/20130606_g1k_3202_samples_ped_population.ext.tsv

# whether to run pilot samples only
run_pilot: True
pilot_samples: /gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/resources/pilot-samples.tsv
pilot_trios: /gpfs/project/projects/medbioinf/users/ebler/minigraph-cactus-paper/genotyping-experiments-chm13/resources/pilot-trios.tsv

# path to executables
pangenie: "singularity exec --bind /:/hilbert eblerjana_eblerjana_pangenie-v2.1.0.sif PanGenie"

additional_read_data:
   HG01123: /gpfs/project/projects/medbioinf/data/hprc_illumina/HG01123/HG01123-111121_S1_L001.fastq.gz
   HG02486: /gpfs/project/projects/medbioinf/data/hprc_illumina/HG02486/HG02486-111121_S6_L002.fastq.gz
   HG02559: /gpfs/project/projects/medbioinf/data/hprc_illumina/HG02559/HG02559-111121_S3_L001.fastq.gz
   NA21309: /gpfs/project/projects/medbioinf/data/hprc_plus/illumina/NA21309/AATGACGC-AATGACGC_S5_L001.fastq.gz
   NA24385: /gpfs/project/projects/medbioinf/users/ebler/hprc/hprc-experiments/HG002-reads/NA24385.fasta.gz 
