# path to reference genome fasta + fai
reference: "path/to/reference.fa"
reference_fai: "path/to/reference.fa.fai"

# path to uncompressed biallelic panel vcf used as input to re-genotyper
# used to produce results provided in "callsets" section below
panel_vcf: "path/to/panel.vcf"

# lists infos and files for each truthset.
truthsets:
 <truthsetname>: # replace by the name of the truthset
  path: "/path/to/truth.vcf.gz" # path to truth set vcf
  callable_regions: "/path/to/callable-regions.bed" # path to BED with callable regions
  vartype: "sv" # variant type. Must be either "snp-indel" or "sv"
  callsets: # re-genotyped vcfs to compare against this truthset
   <callsetname1>: "/path/to/callset1.vcf.gz"
   <callsetname2>: "/path/to/callset2.vcf.gz"

# regions to evaluate in addition to all callable regions 
# in addition to evaluating all callable regions, this provides the option
# to look at subsets of callable regions.
# You can use your own regions by providing the respective BEDs. If none, set ot {}.
regions_to_bed:
 <regionname>: "path/to/region.bed"
